/* Quiz bank — keyed by topic id (matches topics.js). answer = index of correct option. */
var QUIZZES={
 ethics:{title:"Ethical & Professional Standards",questions:[
  {q:"When local law and the CFA Institute Code & Standards conflict, a member should follow:",
   options:["Local law always","The Code & Standards always","The stricter of the two","Whichever the employer prefers"],
   answer:2,explain:"Members must comply with the more strict of applicable law or the Code & Standards."},
  {q:"Which Standard addresses the use of material nonpublic information?",
   options:["Standard I — Professionalism","Standard II — Integrity of Capital Markets","Standard III — Duties to Clients","Standard VI — Conflicts of Interest"],
   answer:1,explain:"Insider trading falls under Standard II(A), Material Nonpublic Information."},
  {q:"GIPS standards apply to:",
   options:["Individual analysts","Firms, on an all-or-nothing basis","Only hedge funds","Regulators"],
   answer:1,explain:"GIPS compliance is claimed at the firm level and must be firm-wide — partial compliance is not allowed."},
  {q:"Disclosing referral fees to clients is required under which Standard?",
   options:["Loyalty to employer","Conflicts of Interest","Suitability","Record retention"],
   answer:1,explain:"Standard VI(C) requires disclosure of any compensation for referrals."},
  {q:"A member who fails to maintain professional competence violates the duty to:",
   options:["Promote market integrity","Maintain and improve competence","Disclose conflicts","Preserve confidentiality"],
   answer:1,explain:"The Code requires members to maintain and improve their professional competence."}
 ]},
 quant:{title:"Quantitative Methods",questions:[
  {q:"The geometric mean return is always:",
   options:["Greater than the arithmetic mean","Less than or equal to the arithmetic mean","Equal to the median","Independent of volatility"],
   answer:1,explain:"For any varying return series, the geometric mean ≤ arithmetic mean; equality only if all returns are identical."},
  {q:"A Type I error occurs when you:",
   options:["Reject a true null hypothesis","Fail to reject a false null","Use the wrong test statistic","Have too small a sample"],
   answer:0,explain:"Type I = rejecting a true null (false positive); its probability equals the significance level α."},
  {q:"The Central Limit Theorem states that the sampling distribution of the sample mean:",
   options:["Is always skewed","Approaches normal as sample size increases","Equals the population distribution","Has zero variance"],
   answer:1,explain:"Regardless of the population shape, the distribution of the sample mean tends to normal as n grows."},
  {q:"Coefficient of variation is calculated as:",
   options:["Mean / σ","σ / mean","σ²/ mean","mean × σ"],
   answer:1,explain:"CV = standard deviation / mean — a measure of risk per unit of return."},
  {q:"If a distribution is positively (right) skewed, then generally:",
   options:["Mean < median","Mean = median","Mean > median","Median = mode only"],
   answer:2,explain:"Right skew pulls the mean above the median due to the long right tail."}
 ]},
 econ:{title:"Economics",questions:[
  {q:"Pricing power is generally highest under:",
   options:["Perfect competition","Monopolistic competition","Oligopoly","Monopoly"],
   answer:3,explain:"A monopoly faces no direct competition and has the greatest pricing power."},
  {q:"Expansionary monetary policy typically involves:",
   options:["Raising interest rates","Lowering interest rates / increasing money supply","Increasing taxes","Cutting government spending"],
   answer:1,explain:"Central banks expand by lowering rates and increasing the money supply to stimulate activity."},
  {q:"GDP by the expenditure approach equals:",
   options:["C + I + G + (X − M)","Wages + profits","Consumption only","Exports − imports"],
   answer:0,explain:"GDP = Consumption + Investment + Government spending + Net exports."},
  {q:"If the base/price currency appreciates, the other currency has:",
   options:["Appreciated","Depreciated","Stayed fixed","Become the reserve currency"],
   answer:1,explain:"Exchange rates are relative — one currency appreciating means the other depreciates."},
  {q:"A tariff on imports generally:",
   options:["Lowers domestic prices","Raises domestic prices and reduces imports","Has no effect","Increases consumer surplus"],
   answer:1,explain:"Tariffs raise the domestic price of imports, protecting local producers but reducing consumer surplus."}
 ]},
 fsa:{title:"Financial Statement Analysis",questions:[
  {q:"In a period of rising prices, FIFO results in:",
   options:["Higher COGS, lower net income","Lower COGS, higher net income & inventory","Lower inventory value","Higher taxes than LIFO only via COGS"],
   answer:1,explain:"FIFO expenses older (cheaper) costs first → lower COGS, higher income, and higher ending inventory."},
  {q:"The DuPont (3-part) decomposition of ROE multiplies:",
   options:["Margin × turnover × leverage","Current × quick × cash","Price × volume × cost","Debt × equity × assets"],
   answer:0,explain:"ROE = Net profit margin × Total asset turnover × Financial leverage."},
  {q:"Cash paid to suppliers appears in which section of the cash flow statement?",
   options:["Operating","Investing","Financing","Equity"],
   answer:0,explain:"Payments to suppliers are operating cash flows (CFO)."},
  {q:"The accounting equation is:",
   options:["Assets = Liabilities − Equity","Assets = Liabilities + Equity","Equity = Assets + Liabilities","Liabilities = Assets + Equity"],
   answer:1,explain:"Assets = Liabilities + Equity — the foundation of the balance sheet."},
  {q:"LIFO is permitted under:",
   options:["IFRS only","US GAAP only","Both","Neither"],
   answer:1,explain:"LIFO is allowed under US GAAP but prohibited under IFRS."}
 ]},
 corporate:{title:"Corporate Issuers",questions:[
  {q:"The after-tax cost of debt is:",
   options:["r_d × tax rate","r_d × (1 − tax rate)","r_d + tax rate","r_d / (1 − tax rate)"],
   answer:1,explain:"Interest is tax-deductible, so after-tax cost of debt = r_d × (1 − tax rate)."},
  {q:"A project should be accepted when its NPV is:",
   options:["Negative","Zero","Greater than zero","Equal to the IRR"],
   answer:2,explain:"Positive NPV means the project adds value; accept it."},
  {q:"When NPV and IRR conflict for mutually exclusive projects, you should rely on:",
   options:["IRR","NPV","Payback period","Profitability index only"],
   answer:1,explain:"NPV is theoretically superior because it assumes reinvestment at the cost of capital and measures value added."},
  {q:"Which cost should be ignored in capital budgeting?",
   options:["Opportunity cost","Sunk cost","Incremental cost","Externalities"],
   answer:1,explain:"Sunk costs are already incurred and irrelevant to the decision."},
  {q:"Higher financial leverage:",
   options:["Reduces both risk and return","Magnifies both gains and losses","Has no effect on equity returns","Lowers the cost of equity"],
   answer:1,explain:"Fixed financing costs magnify the variability of returns to equity holders."}
 ]},
 equity:{title:"Equity Investments",questions:[
  {q:"The Gordon constant-growth model values a stock as:",
   options:["D₁ × (r − g)","D₁ / (r − g)","D₀ / r","(r − g) / D₁"],
   answer:1,explain:"V₀ = D₁ / (r − g), valid only when r > g and growth is constant."},
  {q:"A price-weighted index is most distorted by:",
   options:["Large-cap stocks","High-priced stocks and stock splits","Equal weighting","Dividend yields"],
   answer:1,explain:"Price weighting gives high-priced stocks more influence and is affected by splits."},
  {q:"Semi-strong market efficiency implies prices reflect:",
   options:["Past prices only","All public information","All information including private","No information"],
   answer:1,explain:"Semi-strong form: all publicly available information is already reflected in prices."},
  {q:"Sustainable growth rate equals:",
   options:["ROE / payout","Retention ratio × ROE","Dividend yield × ROE","1 − ROE"],
   answer:1,explain:"g = retention ratio (b) × ROE."},
  {q:"Buying on margin uses:",
   options:["Only the investor's own cash","Borrowed funds to amplify position","Short selling","No leverage"],
   answer:1,explain:"Margin trading borrows funds, magnifying both gains and losses."}
 ]},
 fixed:{title:"Fixed Income",questions:[
  {q:"Bond prices and yields move:",
   options:["In the same direction","Inversely","Independently","Only with coupon changes"],
   answer:1,explain:"As required yield rises, the present value of cash flows (price) falls — an inverse relationship."},
  {q:"All else equal, duration is higher for a bond with:",
   options:["Higher coupon","Shorter maturity","Longer maturity and lower coupon","Higher yield"],
   answer:2,explain:"Longer maturity, lower coupon, and lower yield each increase interest-rate sensitivity (duration)."},
  {q:"A bond trading at a premium has a coupon rate that is:",
   options:["Below its YTM","Equal to its YTM","Above its YTM","Zero"],
   answer:2,explain:"Coupon > yield → price above par (premium)."},
  {q:"Convexity adjustment to a price-change estimate is:",
   options:["Always negative","A correction improving the duration estimate","Irrelevant for small moves only","The same as duration"],
   answer:1,explain:"Convexity captures curvature, improving the linear duration estimate especially for large rate moves."},
  {q:"Which is an example of a bond with an embedded option benefiting the issuer?",
   options:["Putable bond","Convertible bond","Callable bond","Plain vanilla bond"],
   answer:2,explain:"A call option lets the issuer redeem early (e.g., when rates fall) — it benefits the issuer."}
 ]},
 deriv:{title:"Derivatives",questions:[
  {q:"Put–call parity is expressed as:",
   options:["C + PV(X) = P + S₀","C − P = X","P = C + S₀","C × P = S₀"],
   answer:0,explain:"C + PV(X) = P + S₀ links call, put, strike, and underlying under no-arbitrage."},
  {q:"Compared with forwards, futures are:",
   options:["Customized and OTC","Standardized and marked to market daily","Always cheaper","Free of credit risk only via collateral"],
   answer:1,explain:"Futures are exchange-traded, standardized, and settled daily (marked to market)."},
  {q:"The intrinsic value of a call option is:",
   options:["max(0, X − S)","max(0, S − X)","S − X always","X − S always"],
   answer:1,explain:"A call's intrinsic value = max(0, S − X)."},
  {q:"In an options contract, the party with the obligation (not the right) is the:",
   options:["Long","Holder","Short (writer)","Exchange"],
   answer:2,explain:"The option writer (short) has the obligation; the long holds the right."},
  {q:"Option value equals:",
   options:["Intrinsic value only","Time value only","Intrinsic value + time value","Strike − premium"],
   answer:2,explain:"Total option value = intrinsic value + time value."}
 ]},
 alts:{title:"Alternative Investments",questions:[
  {q:"\"2 and 20\" refers to:",
   options:["2% return and 20% risk","2% management fee + 20% of profits","20-year lockup","2 funds, 20 investors"],
   answer:1,explain:"A common hedge-fund fee structure: 2% management fee plus 20% incentive fee on profits."},
  {q:"A high-water mark ensures that:",
   options:["Fees are charged on losses","Incentive fees aren't charged twice on the same gains","Returns are guaranteed","Liquidity is daily"],
   answer:1,explain:"A high-water mark requires recovering prior losses before new incentive fees apply."},
  {q:"The J-curve is most associated with:",
   options:["Commodities","Private equity","REITs","Treasury bonds"],
   answer:1,explain:"PE funds often show early negative returns (fees, slow deployment) then later gains — the J-curve."},
  {q:"A key portfolio benefit of alternatives is:",
   options:["High liquidity","Low correlation with traditional assets","Low fees","Full transparency"],
   answer:1,explain:"Low correlation provides diversification, though at the cost of liquidity, fees, and transparency."},
  {q:"Commodity exposure is most commonly obtained through:",
   options:["Direct physical storage","Futures contracts","Common stock dividends","Bank deposits"],
   answer:1,explain:"Investors typically gain commodity exposure via futures rather than storing physical goods."}
 ]},
 pm:{title:"Portfolio Management",questions:[
  {q:"The CAPM expected return equals:",
   options:["R_f + β(R_m − R_f)","R_m − R_f","β × R_m","R_f × β"],
   answer:0,explain:"E(R) = R_f + β[E(R_m) − R_f], the Security Market Line."},
  {q:"Which risk is rewarded with higher expected return?",
   options:["Unsystematic risk","Systematic (market) risk","Company-specific risk","Diversifiable risk"],
   answer:1,explain:"Only systematic risk is compensated; unsystematic risk can be diversified away."},
  {q:"The document that guides the entire portfolio process is the:",
   options:["Balance sheet","Investment Policy Statement (IPS)","Prospectus","10-K"],
   answer:1,explain:"The IPS sets objectives and constraints and drives planning, execution, and feedback."},
  {q:"A security plotting above the SML is:",
   options:["Overvalued","Fairly valued","Undervalued","Risk-free"],
   answer:2,explain:"Above the SML means it offers more return than required for its beta — undervalued."},
  {q:"The correct order of the portfolio management process is:",
   options:["Execution → Planning → Feedback","Planning → Execution → Feedback","Feedback → Planning → Execution","Planning → Feedback → Execution"],
   answer:1,explain:"Plan (IPS, strategy) → Execute (build portfolio) → Feedback (monitor & rebalance)."}
 ]}
};
